[project]
name = "my project"
revision = "1.0"

[profiles.default]
DEVENV_FLAKE_DIR = { description = "chufang flake.nix path", required = false }
LOCAL_CHUFANG = { description = "chufang local repository path", required = false }
GITHUB_TOKEN = { description = "GitHub PAT (Personal Access Token) to avoid GitHub API rate limiting (403 Rate Limit) when fetching Nix Flake resources", required = false }

[profiles.development]
