[project]
name = "my project"
revision = "1.0"

[profiles.default]
GITHUB_TOKEN = { description = "GitHub PAT (Personal Access Token) to avoid GitHub API rate limiting (403 Rate Limit) when fetching Nix Flake resources", required = false }

[profiles.development]
