[project]
name = "typewriter"
revision = "1.0"

[providers]
development_env = "env://"
development_dotenv = "dotenv:.secrets/development.secrets"

[profiles.default]
CHUFANG_FLAKE_DIR = { description = "chufang flake.nix path", required = true }
CHUFANG_LOCAL_DIR = { description = "chufang local repository path", required = false }
GITHUB_TOKEN = { description = "GitHub PAT (Personal Access Token) to avoid GitHub API rate limiting (403 Rate Limit) when fetching Nix Flake resources, format as github.com=ghp_AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA or fine-grained token github.com/ORG/REPO=ghp_AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", required = false }

[profiles.development]
CHUFANG_FLAKE_DIR = { description = "chufang flake.nix path", providers = [ "development_env" ] }
CHUFANG_LOCAL_DIR = { description = "chufang local repository path", providers = [ "development_env" ] }
GITHUB_TOKEN = { description = "GitHub PAT (Personal Access Token) to avoid GitHub API rate limiting (403 Rate Limit) when fetching Nix Flake resources, format as github.com=ghp_AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA or fine-grained token github.com/ORG/REPO=ghp_AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", providers = [ "development_dotenv" ]}
